server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydb;MODE=MySQL;NON_KEYWORDS=USER,ORDER
    username: root
  cloud:
    zookeeper:
      discovery:
        enabled: true
      connect-string: localhost:2181